AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Description: >
  Responsible for Access + Modifications to Application Configuration Data

# Parameters:

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:

  ConfigurationBucket:
    Description: S3 Bucket with Application Config data
    Value: !Ref S3Bucket